import type { NextPage } from 'next';
import Head from 'next/head';
import { Tabs } from '../components/Tabs/Tabs';
import { Navbar } from '../components/Navbar/Navbar';
import { Search } from '../components/Search/Search';
import { Filters } from '../components/Filters/Filters';
import { Footer } from '../components/Footer/Footer';
import { Catalogue } from '../components/Catalogue/Catalogue';
import { useState } from 'react';
import { Modal } from '../components/shared/Modal/Modal';

const Home: NextPage = () => {
  // const [price, setPrice] = useState(0);
  const [activeModal, setActiveModal] = useState('');
  return (
    <div className="flex justify-center items-start h-[100vh]">
      <Head>
        <title>SUAV BEAUTY</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="container flex justify-start items-center w-[430px] flex-col h-full border relative">
        <Navbar />
        <section className="container h-[167px] relative p-[18px] pt-[11px] shadow-[0_2px_3px_#B7B7B74D]">
          <Tabs />
          <Search />
          <Filters setActiveModal={setActiveModal} />
        </section>
        <section className="container flex justify-start items-center h-full p-[12px] pb-0 pt-0 overflow-hidden">
          <Catalogue />
        </section>
        <footer className="container flex justify-around items-center min-h-[60px] shadow-[0_-2px_3px_#B7B7B74D]">
          <Footer />
        </footer>
        {activeModal === 'price' && (
          <Modal activeModal={activeModal} setActiveModal={setActiveModal} />
        )}
      </main>
    </div>
  );
};

export default Home;
