import type { NextPage } from 'next';
import Head from 'next/head';
import { Tabs } from '../components/Tabs/Tabs';
import { Navbar } from '../components/Navbar/Navbar';
import { Search } from '../components/Search/Search';
import { Filters } from '../components/Filters/Filters';
import { Footer } from '../components/Footer/Footer';
import { Catalogue } from '../components/Catalogue/Catalogue';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Modal } from '../components/shared/Modal/Modal';
import {
  IFiltersProps,
  TCurrentSection,
} from '../components/Filters/filters.interface';

const Home: NextPage<IFiltersProps> = () => {
  const topCatalogueRef = useRef<HTMLDivElement>(null);

  const [activeModal, setActiveModal] = useState('');
  const [filters, setFilters] = useState<IFiltersProps>({
    currentSection: TCurrentSection.HOME,
    byPrice: '0',
    byExpertise: '0',
    byCategory: '',
  });

  const scrollUp = useCallback(() => {
    topCatalogueRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [topCatalogueRef]);

  useEffect(scrollUp, [topCatalogueRef, filters]);

  return (
    <div className="flex justify-center items-start h-[100vh] container">
      <Head>
        <title>SUAV BEAUTY</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="container flex justify-start items-center w-[430px] flex-col h-full border relative">
        <Navbar />
        <section className="container h-[167px] relative p-[18px] pt-[11px] shadow-[0_2px_3px_#B7B7B74D]">
          <Tabs />
          <Search />
          <Filters
            setActiveModal={setActiveModal}
            filters={filters}
            setFilters={setFilters}
          />
        </section>
        <section className="container flex justify-start items-center h-fit p-[12px] pb-0 pt-0 overflow-hidden">
          <Catalogue filters={filters} />
        </section>
        <footer className="container flex justify-around items-center min-h-[60px] shadow-[0_-2px_3px_#B7B7B74D]">
          <Footer filters={filters} setFilters={setFilters} />
        </footer>
        {activeModal === 'price' && (
          <Modal
            activeModal={activeModal}
            setActiveModal={setActiveModal}
            setFilters={setFilters}
            filters={filters}
            scrollUp={scrollUp}
          />
        )}
      </main>
    </div>
  );
};

export default Home;
