export const objItems = [
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 100,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 200,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 300,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 400,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 500,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 600,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 700,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 800,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 900,
  },
  {
    title: 'Braids',
    madedBy: 'Kailey Lash',
    takeTime: 1,
    place: 'In House',
    process: 'Customization',
    price: 1000,
  },
];
